### ISSUE TITLE
Error when running online demo

### ISSUE THREAD

**Issue by dgreensp** [Storyyeller/cubiml-demo#2]
At https://storyyeller.github.io/cubiml-demo/demo.html , run code as-is.  It looks like `n-1` is being parsed as `n(-1)`.

Btw, thanks for taking the time to make and write up cubiml.  I'm looking forward to getting farther in my implementation!  What is the best way to contact you if I want to show you my implementation sometime or ask questions?  I've seen you on Reddit.  I can open issues for questions, in some cases.

**Comment by Storyyeller** [comment]
Thanks for reporting this! I'm not sure how I missed it when I made the change. 

As for contact, I think Reddit DM, email, or Github would all work.
