### ISSUE TITLE
Unsound type annotation

### ISSUE THREAD

**Issue by mbillingr** [Storyyeller/cubiml-demo#7]
Hi there,

Thanks for sharing an amazing concept in a series of super readable blog posts!

While experimenting with various extensions to the cubiml language, I stumbled over an issue that I believe to be an unsoundness in type annotations. My first thought was that I messed something up, but it is reproducible in the web-based demo, so it is probably not my fault after all.

Here is a small implementation of a linked list:
```sml
let nil = `Nil {};

let cons = fun h ->
    (fun t -> `Cons {h=h; t=t}
        : [`Nil of _ | `Cons of {h:_; t:'list}] as 'list -> 'list)
;

let rec map = fun f -> fun lst ->
    match lst with
        | `Nil _ -> `Nil _
        | `Cons p -> `Cons {h=f p.h; t=(map f) p.t}
;

let sqr = fun x -> x * x;

(map sqr) ((cons 2) ((cons "foo") nil))
```

Output:
```
 `Cons{h=4; t=`Cons{h=NaN; t=`Nil{}}}
```

I think this should produce a type error because a function that accepts integers is mapped over a list that contains int and string items. Instead, the type checker accepts the program and at runtime multiplying the string presumably results in NaN (at least that's my conclusion without knowing any Javascript).

When I remove the type annotation in the `cons` function I get the expected type error (shortened):
```
TypeError: Value is required to be a integer here,
let sqr = fun x -> x * x;
                       ^ 

But that value may be a string originating here.
(map sqr) ((cons 2) ((cons "foo") nil))
                           ^~~~~       
```

So, uhm... adding an annotation makes the type checker accept a faulty program. This doesn't seem quite right to me...

**Comment by Storyyeller** [comment]
Thanks for the report. That does look bad.

**Comment by Storyyeller** [comment]
I was able to reduce the bug down to just `({a=4; b="foo"}: {a:int as 'i; b:'i})
`. Seems like there must be an issue with type aliases.

**Comment by Storyyeller** [comment]
Should be fixed now. Thanks for finding this.
